#ifndef INTERNAL_HEX_H
#define INTERNAL_HEX_H

#define OPERATE_TYPE_ADDITION       (0U)
#define OPERATE_TYPE_SUBSTRACTION   (1U)
#define OPERATE_TYPE_MULTIPLICATION (2U)
#define OPERATE_TYPE_DIVISION       (3U)

#endif // !INTERNAL_HEX_H

